name: Deploy Eat For Eat

on:
  push:
    branches:
      - main  # Awla s-smiya dial l-branch dyalk

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}  # T-akked men s-smiya
          username: ${{ secrets.REMOTE_USER }} # T-akked men s-smiya
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Sta3mel KEY f blast PASSWORD
          script: |
            cd /var/www/eat_for_eat
            git fetch --all
            git reset --hard origin/main
            npm install
            npm run build
            # T-akked blli hna 'dist' mashi 'out'
            pm2 delete eat-for-eat || true
            pm2 start serve --name "eat-for-eat" -- -s dist -l 3001
            pm2 save